sudo: false
language: python
python:
- 3.6
branches:
  only:
  - master # build master branch only

env:
  global:
  - ALI_IP: 8.136.13.58
  - GIT_USER: voidking
  - GITEE_PAGES_REPO: gitee.com/voidking/voidking.git

addons:
  ssh_known_hosts: 
  - 8.136.13.58

before_install:
- echo ${ID_RSA} | base64 -d > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa

script:
- ssh voidking@${ALI_IP} "cd /opt/nginx/work/voidking/ && git pull --force --quiet \"https://${GIT_USER}:${GITEE_TOKEN}@${GITEE_PAGES_REPO}\" master:master"

after_success:
- echo "deploy success"